# basic options
title: Personal page
author: Kirill Grischuk
email: kirya522@gmail.com
description: My personal page
twitter_username: kirya522
github_username:  kirya522

# Build settings
markdown: kramdown
theme: minima